# Generated by Django 3.2.5 on 2021-08-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20, verbose_name='Email Address')),
                ('adviser', models.CharField(max_length=20, verbose_name='Adviser')),
                ('contact', models.DecimalField(decimal_places=0, default='', max_digits=11, verbose_name='Contact Number')),
                ('org', models.CharField(choices=[('', ''), ('ACETS', 'ASSOCIATION OF CIVIL ENGINEERING TECHNOLOGY STUDENTS'), ('ACTS', 'ASSOCIATION OF COMPUTER TECHNOLOGY STUDENTS'), ('APPLETS', 'ASSOCIATION OF POWER PLANT ENGINEERING TECHNOLOGY STUDENTS'), ('ARTISTS` CLUB', 'ARTISTS` CLUB'), ('EHS', 'ENGINEERING HONOR SOCIETY'), ('FEO', 'FUTURE EDUCATORS’ ORGANIZATION'), ('METALS', 'MECHANICAL ENGINEERING TECHNOLOGY'), ('PICE', 'PHILIPPINE INSTITUTE OF CIVIL ENGINEERS'), ('ODD', 'OTTO DE DION'), ('SAC', 'STUDENT AMBASSADOR FOR CHRIST'), ('SETS', 'SOCIETY OF ELECTRONICS TECHNOLOGY STUDENT'), ('SRC', 'STUDENTS RIDERS CLUB ')], default='', max_length=50, null=True, verbose_name='Organization Name')),
            ],
        ),
        migrations.CreateModel(
            name='ReportsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuE', models.CharField(default='', max_length=20, verbose_name='Accomplishment Report Status')),
                ('file_link', models.URLField(default='', max_length=100, verbose_name='Accomplishment Link (Google Drive)')),
                ('date', models.DateField(default='')),
                ('OrganizationName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tupc.organizationinfo', verbose_name='Organization Name')),
            ],
        ),
        migrations.CreateModel(
            name='OfficersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=20, verbose_name='firstname')),
                ('last', models.CharField(max_length=20, verbose_name='lastname')),
                ('position', models.CharField(max_length=20, verbose_name='Position')),
                ('academic', models.CharField(max_length=20, verbose_name='Academic Year')),
                ('student', models.CharField(max_length=20, unique=True, verbose_name='Student ID Number')),
                ('sex', models.CharField(choices=[('', ''), ('male', 'Male'), ('female', 'Female')], default='', max_length=20)),
                ('course', models.CharField(choices=[('', ''), ('BACHELOR OF SCIENCE IN CIVIL ENGINEERING', 'BSCE'), ('BACHELOR OF SCIENCE IN ELECTRICAL ENGINEERING', 'BSEE'), ('BACHELOR OF SCIENCE IN MECHANICAL ENGINEERING', 'BSME'), ('BET-ELECTRICAL TECHNOLOGY', 'BET-ET'), ('BET-INDUSTRIAL AUTOMATION TECHNOLOGY', 'BET-ESET'), ('BET-COMPUTER ENGINEERING TECHNOLOGY', 'BET-COET'), ('BET-CIVIL TECHNOLOGY', 'BET-CT'), ('BET-MECHANICAL ENGINEERING TECHNOLOGY', 'BET-MT'), ('BET-AUTOMOTIVE TECHNOLOGY', 'BET-MT'), ('BET-MECHANICALENGINEERING TECHNOLOGY', 'BET-MT'), ('BET-POWER PLANT TECHNOLOGY', 'BET-PPT'), ('BSIE-INFORMATION COMMUNICATION TECHNOLOGY', 'BSIE-ICT'), ('BSIE-HOME ECONOMICS', 'BSIE-HE'), ('BTTE-AUTOMOTIVE', 'BTTE-AU'), ('BTTE-ELECTRICAL', 'BTTE-EI'), ('BTTE-ELECTRONICS', 'BTTE-E'), ('BTTE-AIR CONDITIONING', 'BTTE-HVACT'), ('BTTE-COMPUTER PROGRAMMING', 'BTTE-CP')], default='', max_length=50, null=True)),
                ('OrganizationName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tupc.organizationinfo', verbose_name='Organization Name')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitiesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=20, verbose_name='Activity Name')),
                ('budget', models.IntegerField(verbose_name='Est. Budget')),
                ('target', models.CharField(max_length=20, verbose_name='Target Participants')),
                ('number', models.IntegerField(verbose_name='No. of Participants')),
                ('officers', models.IntegerField(verbose_name='No. of Officers Involved')),
                ('faculty', models.CharField(max_length=20, verbose_name='Faculty In-charged')),
                ('description', models.TextField(max_length=20, verbose_name='Activity Description')),
                ('OrganizationName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tupc.organizationinfo', verbose_name='Organization Name')),
            ],
        ),
    ]
