# Generated by Django 3.2.5 on 2021-08-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationinfo',
            name='email',
        ),
        migrations.AlterField(
            model_name='reportsinfo',
            name='file_link',
            field=models.URLField(default='', max_length=100, verbose_name='Accomplishment Report (Link)'),
        ),
    ]
