# Generated by Django 3.2.5 on 2021-08-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tupc', '0004_alter_organizationinfo_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officersinfo',
            name='sex',
            field=models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=20),
        ),
    ]
